#ifndef __GS_NET_PROTOCOL_H__
#define __GS_NET_PROTOCOL_H__

enum GS_PROTOCOL_BASE_VALUE
{
	GS_PROTOCOL_VALUE_NONE = 0x0000,
	GS_PROTOCOL_VALUE_LOGIN = 0x0100,
	GS_PROTOCOL_VALUE_BASE = 0x0200,
	GS_PROTOCOL_VALUE_CONTROL = 0x0300,
};

enum GS_PROTOCOL_LOGIN
{
	GS_PROTOCOL_LOGIN = GS_PROTOCOL_VALUE_LOGIN,

	GS_PROTOCOL_LOGIN_LOGIN_REQ,
	GS_PROTOCOL_LOGIN_LOGIN_ACK,
};

enum GS_PROTOCOL_BASE
{
	GS_PROTOCOL_BASE = GS_PROTOCOL_VALUE_BASE,

	GS_PROTOCOL_BASE_CONNECT_REQ,
	GS_PROTOCOL_BASE_CONNECT_ACK,

	GS_PROTOCOL_BASE_DISCONNECT_REQ,
	GS_PROTOCOL_BASE_DISCONNECT_ACK,
};

enum GS_PROTOCOL_CONTROL
{
	GS_PROTOCOL_CONTROL = GS_PROTOCOL_VALUE_CONTROL,

	GS_PROTOCOL_CONTROL_LOADMAP_REQ,
	GS_PROTOCOL_CONTROL_LOADMAP_ACK,

	GS_PROTOCOL_CONTROL_SHUTDOWN_REQ,
	GS_PROTOCOL_CONTROL_SHUTDOWN_ACK,
	GS_PROTOCOL_CONTROL_KILL_REQ,
};

#endif
