#ifndef __NET_PROTOCOL_H__
#define __NET_PROTOCOL_H__

enum PROTOCOL_BASE_VALUE
{
	PROTOCOL_VALUE_NONE								= 0x0000,
	PROTOCOL_VALUE_LOGIN							= 0x0100,
	PROTOCOL_VALUE_BASE								= 0x0200,
	PROTOCOL_VALUE_LOBBY							= 0x0300,
	PROTOCOL_VALUE_LOADOUT							= 0x0400,	
	PROTOCOL_VALUE_ROOM								= 0x0500,
	PROTOCOL_VALUE_USER								= 0x0600,
	PROTOCOL_VALUE_DEDI								= 0x0700,
};

enum Protocol_Login
{
	PROTOCOL_LOGIN									= PROTOCOL_VALUE_LOGIN,

	PROTOCOL_LOGIN_INPUT_REQ,						// 로그인
	PROTOCOL_LOGIN_INPUT_ACK,						// 로그인

	PROTOCOL_LOGIN_WEBKEY_REQ,						// 웹 로그인
	PROTOCOL_LOGIN_WEBKEY_ACK,						// 웹 로그인

	PROTOCOL_LOGOUT_REQ,							// 로그 아웃
	PROTOCOL_LOGOUT_ACK,							// 로그 아웃
};

enum PROTOCOL_BASE
{
	PROTOCOL_BASE									= PROTOCOL_VALUE_BASE,

	PROTOCOL_BASE_CONNECT_REQ,
	PROTOCOL_BASE_CONNECT_ACK,

	PROTOCOL_BASE_CONNECT_AUTH_REQ,
	PROTOCOL_BASE_CONNECT_AUTH_ACK,

	PROTOCOL_BASE_DISCONNECT_REQ,
	PROTOCOL_BASE_DISCONNECT_ACK,

	PROTOCOL_BASE_HEARTBIT_REQ,
	PROTOCOL_BASE_HEARTBIT_ACK,

	PROTOCOL_BASE_NOTICE_REQ,
	PROTOCOL_BASE_NOTICE_ACK,
};

enum PROTOCOL_DEDI
{
	PROTOCOL_DEDI									= PROTOCOL_VALUE_DEDI,

	PROTOCOL_DEDI_START_REQ,
	PROTOCOL_DEDI_START_ACK,

	PROTOCOL_DEDI_LOADED_REQ,
	PROTOCOL_DEDI_LOADED_ACK,

	PROTOCOL_DEDI_END_REQ,
	PROTOCOL_DEDI_END_ACK,
};

enum PROTOCOL_USER
{
	PROTOCOL_USER									= PROTOCOL_VALUE_USER,

	PROTOCOL_USER_INFO_LOAD_REQ,
	PROTOCOL_USER_INFO_LOAD_ACK,

	PROTOCOL_USER_INFO_SAVE_REQ,
	PROTOCOL_USER_INFO_SAVE_ACK,

	PROTOCOL_USER_CHANGE_NICK_REQ,
	PROTOCOL_USER_CHANGE_NICK_ACK,
};

enum PROTOCOL_ROOM
{
	PROTOCOL_ROOM									= PROTOCOL_VALUE_ROOM,

	PROTOCOL_ROOM_CREATE_REQ,						// 방 생성 요청
	PROTOCOL_ROOM_CREATE_ACK,

	PROTOCOL_ROOM_ENTER_REQ,						// 방 입장
	PROTOCOL_ROOM_ENTER_ACK,

	PROTOCOL_ROOM_ENTER_TRANS_REQ,					// 다른 유저 방 입장
	PROTOCOL_ROOM_ENTER_TRANS_ACK,

	PROTOCOL_ROOM_LEAVE_REQ,						// 방 퇴장
	PROTOCOL_ROOM_LEAVE_ACK,

	PROTOCOL_ROOM_LEAVE_TRANS_REQ,					// 다른 유저 방 퇴장
	PROTOCOL_ROOM_LEAVE_TRANS_ACK,

	PROTOCOL_ROOM_QUICK_MATCH_REQ,					// 퀵 매치
	PROTOCOL_ROOM_QUICK_MATCH_ACK,

	PROTOCOL_ROOM_SLOT_INFO_REQ,					// 다른 유저 정보 요청
	PROTOCOL_ROOM_SLOT_INFO_ACK,

	PROTOCOL_ROOM_OPTION_CHANGE_REQ,				// 방 옵션 변경
	PROTOCOL_ROOM_OPTION_CHANGE_ACK,

	PROTOCOL_ROOM_MAP_VOTE_REQ,						// 맵 투표
	PROTOCOL_ROOM_MAP_VOTE_ACK,

	PROTOCOL_ROOM_MAP_VOTE_TRANS_REQ,
	PROTOCOL_ROOM_MAP_VOTE_TRANS_ACK,				// 맵 투표 결과

	PROTOCOL_ROOM_SLOT_READY_REQ,					// 레뒤 버튼
	PROTOCOL_ROOM_SLOT_READY_ACK,

	PROTOCOL_ROOM_STATE_CHANGE_REQ,					// 방 상태 변경
	PROTOCOL_ROOM_STATE_CHANGE_ACK,

	PROTOCOL_ROOM_SLOT_STATE_CHANGE_REQ,			// 슬롯 상태 변경
	PROTOCOL_ROOM_SLOT_STATE_CHANGE_ACK,
	
	PROTOCOL_ROOM_BATTLE_START_REQ,					// 배틀 시작
	PROTOCOL_ROOM_BATTLE_START_ACK,

	PROTOCOL_ROOM_BATTLE_END_REQ,					// 배틀 종료
	PROTOCOL_ROOM_BATTLE_END_ACK,

	PROTOCOL_ROOM_LIST_REQ,							// Room List
	PROTOCOL_ROOM_LIST_ACK,

	PROTOCOL_ROOM_BATTLE_READY_REQ,					// 배틀 시작
	PROTOCOL_ROOM_BATTLE_READY_ACK,
};

#endif
